### ISSUE TITLE
Publication in W3C accessibility evaluation tools list

### ISSUE THREAD

**Issue by josehilera** [NAB/UBKAccessibilityKit#4]
We have received on the [W3C mailing list](https://lists.w3.org/Archives/Public/public-wai-ert-tools/2020Aug/0012) a suggestion from a user to include UBKAccessibilityKit in the [W3C Web Accessibility evaluation tools list](https://www.w3.org/WAI/ER/tools/submission).
In order to include it, we need the consent of the author of the tool.
If you agree to include UBKAccessibilityKit in the list, please review the data about the tool that the user has sent, and if you want to modify any, you can send the changes to jose.hilera@uah.es, content manager of the list. Or fill out the [submission form for new tools](https://www.w3.org/WAI/ER/tools/submission) . Thanks.

**Comment by ubank-philk** [comment]
Thank you for asking to include UBKAccessibilityKit on the Tools List. We'd love to see it there and have sent along our approvals.
